// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microondas_digital_infra.Contexts;

#nullable disable

namespace microondas_digital_infra.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    partial class SQLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("microondas_digital_infra.EntitiesConfiguration.DbMicroondas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("HoraInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inicio");

                    b.Property<DateTime?>("HoraPausa")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_pausa");

                    b.Property<int>("Minutos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minutos");

                    b.Property<int>("Potencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("potencia");

                    b.Property<int>("Segundos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("segundos");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("microondas");
                });

            modelBuilder.Entity("microondas_digital_infra.EntitiesConfiguration.DbProgramaAquecimento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Alimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("alimento");

                    b.Property<char?>("Caractere")
                        .HasColumnType("TEXT")
                        .HasColumnName("caractere");

                    b.Property<string>("Instrucoes")
                        .HasColumnType("TEXT")
                        .HasColumnName("instrucoes");

                    b.Property<int>("Minutos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minutos");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int>("Potencia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("potencia");

                    b.Property<int>("Segundos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("segundos");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("programa_aquecimento");
                });

            modelBuilder.Entity("microondas_digital_infra.EntitiesConfiguration.DbUsuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("microondas_digital_infra.EntitiesConfiguration.DbMicroondas", b =>
                {
                    b.HasOne("microondas_digital_infra.EntitiesConfiguration.DbUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("microondas_digital_infra.EntitiesConfiguration.DbProgramaAquecimento", b =>
                {
                    b.HasOne("microondas_digital_infra.EntitiesConfiguration.DbUsuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
